# Generated by Django 4.1.7 on 2023-02-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sena_research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='topic',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
