# Generated by Django 4.1.7 on 2023-04-06 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sena_research', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': 'Services'},
        ),
    ]
