# Generated by Django 4.1.7 on 2023-06-16 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sena_research', '0002_order_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='promoter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
