# Generated by Django 4.1.7 on 2023-07-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sena_research', '0004_alter_order_promoter_alter_order_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=150),
        ),
    ]
