# Generated by Django 4.1.7 on 2023-04-15 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sena_research', '0005_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact Us'},
        ),
    ]
