# Generated by Django 4.1.7 on 2023-04-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoter',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('NonActive', 'NonActive')], default='NonActive', max_length=20),
        ),
    ]
