# Generated by Django 4.1.7 on 2023-05-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_alter_promoter_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoter',
            name='image',
            field=models.ImageField(default='services/33_003_4DLxqvJ.jpg', upload_to='Users/'),
        ),
    ]
