# Generated by Django 4.1.7 on 2023-04-06 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_alter_promoter_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promoter',
            options={'verbose_name_plural': 'Promoters'},
        ),
    ]
