# Generated by Django 4.1.7 on 2023-03-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_remove_promoter_bio_remove_promoter_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoter',
            name='bio',
            field=models.TextField(default='random text'),
            preserve_default=False,
        ),
    ]
