# Generated by Django 4.1.7 on 2023-06-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_alter_promoter_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoter',
            name='academic_division',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promoter',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='promoter',
            name='degree',
            field=models.CharField(blank=True, choices=[('Master', 'Master'), ('Doctort', 'Doctort')], max_length=20),
        ),
        migrations.AlterField(
            model_name='promoter',
            name='major',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promoter',
            name='rank',
            field=models.CharField(blank=True, choices=[('Professor', 'Professor'), ('Lecturer professor A', 'Lecturer professor A'), ('Lecturer professor B', 'Lecturer professor B'), ('Assistant Professor A', 'Assistant Professor B'), ('PhD student', 'PhD student')], max_length=50),
        ),
    ]
