# Generated by Django 4.1.7 on 2023-06-01 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0004_alter_promoter_academic_division_alter_promoter_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promoter',
            name='status',
        ),
    ]
