# Generated by Django 4.1.7 on 2023-04-06 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0004_alter_promoter_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promoter',
            options={'verbose_name': 'Promoter'},
        ),
    ]
