# Generated by Django 4.1.7 on 2023-06-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0005_remove_promoter_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoter',
            name='phone',
            field=models.IntegerField(default=1111),
            preserve_default=False,
        ),
    ]
