# Generated by Django 4.1.7 on 2023-04-09 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0006_alter_promoter_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promoter',
            options={'verbose_name': 'Promoter'},
        ),
    ]
