# Generated by Django 4.1.7 on 2023-06-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0006_promoter_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoter',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
