# Generated by Django 4.1.7 on 2023-04-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0007_alter_promoter_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoter',
            name='image',
            field=models.ImageField(default='ppp', upload_to='Users/'),
            preserve_default=False,
        ),
    ]
