# Generated by Django 4.1.7 on 2023-04-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0008_promoter_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoter',
            name='image',
            field=models.ImageField(default='media/services/33_003_4DLxqvJ.jpg', upload_to='Users/'),
        ),
    ]
